### ISSUE TITLE
General goodtables-ui update

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-ui#28]
# Overview

The same as with https://github.com/frictionlessdata/software/issues/38 - we need to improve code quality and update a few dependencies (bootstrap@4 and full support of goodtables@2 - more tests etc)

# TODO

- [x] rebase on bootstrap 4
- [x] write more tests (esp for the latest `goodtables` version)
- [x] implement customizable colors for different errors

**Comment by cschloer** [comment]
I like color intensity based on weights. There could also be a color tag that allows you to just put in your desired RGB color code?

**Comment by roll** [comment]
Hey @cschloer,

Please take a look at `@2.0.0-alpha.2`:
- https://frictionlessdata.github.io/goodtables-ui/
- https://frictionlessdata.github.io/goodtables-ui/report.html

It now uses `bootstrap4` and supports custom colors - https://github.com/frictionlessdata/goodtables-ui#component-report

**Comment by roll** [comment]
I've added reports validation so it will be great to test it within a real application during the pre-release phase

**Comment by cschloer** [comment]
The hexColor attribute works great. And the bootstrap update is also helpful - no longer need custom css to make it work with bootstrap 4.0. I agree though down the line it would be useful to remove that dependency.

**Comment by roll** [comment]
FIXED in https://github.com/frictionlessdata/goodtables-ui/commit/651d45ef3436eaeaccebf6d05b8f63c5662543b6
