### ISSUE TITLE
Add datapackage support

### ISSUE THREAD

**Issue by roll** [frictionlessdata/goodtables-ui#4]
# Overview

Form component should support data package sources

# Tasks

- [ ] sync `goodtables.io API` with goodtables `validate` function
- [ ] sync JavaScript lib with synced `goodtables.io API`
- [ ] provide datapackage support for UI lib

**Comment by roll** [comment]
@pwalsh 
@amercader 
I think this one is really important to improve our testing power of the whole `goodtables` ecosystem. Target is ability to provide file/datapackage to `try.goodtables.io` without any other settings and validate it. So we will be able go thru many data packages (testing both data and our service) even without adding it to `goodtables.io`.

After `goodtables-py` update we just need to sync `goodtables.io API` with it (which is easy) and update JS/UI libs (which is easy too). Marked it as `planned` to take a look on one of next sprint plannings.

**Comment by amercader** [comment]
The sources referenced by the data package should be URLs right? or are you planning on adding support for uploading zipped datapackage.json + files?

**Comment by roll** [comment]
I think url to JSON will be pretty enough for now.
